branches:
  only:
  - master

language: python

python:
- '2.7'
- '3.4'

script: tox

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://upload.pypi.org/legacy/
    user: bachew
    password:
      secure: R6r/KY7x1Sx1FU2qCsZxf4IPch+CJB4vQUgxPi0YAJTuTTvssiqpOEcrNUmDv67bhD4cCiP4j3iJCZhzuQo60ghwsYvxKMUBb0wOFrz0nG3TzMemL+11VFjhEJ+OJ5l6Y1353opYr+suzLvFQxFcAPHeynieeLRCWcKRKQulFyTUgf5V9TrogobjF0WSWbI0ngQWslQ4/b4so77TJNXQVoFGmi3Ryqu/TRPCF/uF33Z+RsEd9GtGnYsHElwQsVL2rwNEltunTcdnGesRA7B7E6r6wyRFhPoThOHOoWX88P79tTY72OVxNJ2IFg5F6Ps/P9Li6fecLESx3EKtPojxqsoXdbhE4s84O7wyGjU99UIxLOep8nsrbN0ZM/F8kYTSK91cGXF6oLEHIAe8xhd02hQwQzMFAtWR9o+qXGovrJ515z7/5fATn7b24P94ooMUbwvCtfg/+6F8y3y0TS77SpV4XaiNhADKjlfHn3I4lLbIfqsTPjib8Dh996Ra1wzVOrGmYMkf8pZvgTEg7OAeXWmtauaOw/iCWZkbG1JtSj9ZYDM0JGa/48eIO9Wq9bPPPZn3S0FBERZ2tWamZgejMP8x4Mfi8NH08YiATe4IZW08jM2YlZHkuNHV8W9BG6AzezlzdtZaLiFHlPr0RDX+UfM77xWKX/zph5itto8cqZU=
    on:
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
