language: python

python:
- '2.7'
- '3.4'

script: tox

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    user: bachew
    password:
      secure: mzMPDj0HABunqGIGOGNIXtZMsV/JRfGkqUMNimJAXwGU2TuK9ODt6XT6uB6lWnu/PE+iVzcgH19mHog/+Kd8DhX1yAW6Ixh5ZsNnRIK3x/xmNtIbYOULJbLBURVLFrHetmWldeHvwVT5HBlCCbqUx7TRKMJNdnEBwsDvv68SkUntUsE3yc34hsu7SyAN+/E2cecpf4PmyNpd1Jft5dPDtPE+unx23ZcIV1SeZeTJmNagzt0UvLM5ozZ8qzoTs51pY6IHTNZtb44pEWHnx6Sr5MR6nzqU2NIpgdWdyJqdrXIyByhAnTsTgeNSOIRH2pyEGlXSc7GjkAdOIeKb7WFBS3JMPBVwbCcQvSmoLt/GHWcGjjz/+Sz/LmqBd1oF40S9jYgpHY30rX9AeyrREA1vBSi3CWwcgP65WfLXqtPfOl3PLjt44/+FQmA3nX2Spu4DZC1lYAsC9iWPCXMVjtNPlfYvKKA0DrVkUua2Hh/Im+H/bgudyLeVY203i60b+9w4MvnUUi9uSdAlSVDuyYKMips5/d99rm2cdtOXbAJOSx3a83aIp0DaPvSH0GUpkXTTCpOgqDroHG9jcOrLo2jUtWbKNz9Efxw9GK0EVxm6D3mY+HhOq73xC35VneKqixeRin/saQE+ZvlYhpnEtsCt1JJkhUDcS9Ui4S+wrcC4RSY=
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: pypi
    distributions: sdist bdist_wheel
    user: bachew
    server: https://upload.pypi.org/legacy/
    password:
      secure: 0Q2BXRgXxdvftM3gbMSecxXaf9x68UxJwMncfAWmQlnJd7Osl3w2ev93EwqlSHqDYdNCABh0omqWS9BqyiXZ4JHoioSubf/25buYRBm5uKmTcPKaTHOBzsrn/Wj12QbvRcwuAR/fPYFbHpeKm/HfTo88E7FcKScytHYduU3wNm478f5deh8YBixfSySVJxxwIubN6TVVZ9FrohAXJL1C0HnIetr5W/0rflFcSUIbosBWKG6cgeONSudt5nE+Fdr+0/hwYxpuY8MYerx8Apc0wKZCQ5fKo0HemLVC1TWRcViZPJQYzrTIRD/Hg0EYuUP/L+99dJUUZNFuP9YBnKKp71wy1lBLFKQULuHVWEkvg4ACS12p9uGLg3lmNp1tzVS4zny/ZaDkHok5jRUZ8AtfMBMXyjHMwaWvGOTT6RILwIUjKULtiYVssj6GRv2UWtD7R2c1ZOuROx9R4xQrSBSQXoYQQyt5vJqu6aFvVireTwsauTpHuy552rvhrljr0f6BJ0nDQxrg61IiCqn0v6n8h8g7IgzMFqNE1Tpz2NcFVsrF8gkMDYmeLuNL2sjoBF7seTZKYT0j85kjynVK9suZRipLkEpWODcB3TaM37Q6UHpttfy++JOL1pln5tk/EteJbJA2RRjiPk6e/r7vUj4yqLsFfnDX8AcY10kjqeVKUtY=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
